### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#10]
Currently we have PDF document ["Cardano.BM - logging, benchmarking and monitoring"](https://github.com/input-output-hk/iohk-monitoring-framework/blob/develop/docs/IOHK-Monitoring.pdf) automatically generated from our Literate Haskell.

It's a good document, but unfortunately, doesn't explain some basic concepts of `iohk-monitoring-framework` by simple words, and the reader must dive deeply in the source code. So we have to add few additional simple explanations how this system works.

**Comment by denisshevchenko** [comment]
@CodiePP So, https://github.com/input-output-hk/iohk-monitoring-framework/pull/205 is merged.
