### ISSUE TITLE
Issue message counts

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#118]
for monitoring of internal queues: each queue should count the number of messages (by type or by severity) that it forwards. These counters should then be output in a log message every `n` minutes. Then reset. The time between the meassurements should be kept so we can calculate the rate of messages per second for example.
plus: also output the current number of items in the queue

name space: `#messagecounters.` + `ekgview`|`switchboard`|..

**Comment by 365andreas** [comment]
Could be used to give priority to some Messages of the queue.
