### ISSUE TITLE
Logging in 'Sim'

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#119]
MonadProbe defines:
```
withProbe f = do
  p <- newProbe
  runM (f p)
  readProbe p
```
the outcomes are kept in a list: `type ProbeTrace m a = [(Time m, a)]`

can we hook into readProbe and output the outcomes to logging?

Time is `Int` (microseconds), this could be "added" to the real start time to get a valid timestamp.

we probably need to add a new function in `Trace.lhs`: traceTimedItem :: Trace m -> (Timestamp, `a`) -> m ()

**Comment by 365andreas** [comment]
:arrow_up: PR in `ouroboros-network`.

**Comment by coot** [comment]
We are planing to remove `MonadProbe`  it's better to just define it in terms of `MonadSTM`.

**Comment by CodiePP** [comment]
PR 298 in ouroboros-network https://github.com/input-output-hk/ouroboros-network/pull/298
has been merged!
