### ISSUE TITLE
Exception capture at RTS level

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#125]
**Is your feature request related to a problem? Please describe.**
I would like log every exception thrown in the executable, even when it is immediately catched and thus will not be able to notice.

**Describe the solution you'd like**
Hook into the `RTS` and capture every exception.

**Describe alternatives you've considered**
Maybe an easier approach would be to use `DTrace` in GHC.

**Comment by 365andreas** [comment]
That is not easily achievable. It is very tricky.
We could get this for exceptions thrown by our code (changing `throwM`) but we would not be able to do this for external libraries without wrapping them.

Another option could be RTS hooks. However, documentation for hooks (https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#runtime-events) is very limited and exploring this space would be time consuming.

**Comment by avieth** [comment]
>  I would like log every exception thrown in the executable, even when it is immediately catched and thus will not be able to notice.

Why? This wouldn't be very useful information. If a program catches an exception and does not re-throw it, is it really an exception from the outside view? Any program which uses that program should not be able to know that there was an exception. It's an abstraction leak, and a very noisy one that wouldn't help with anything.

**Comment by erikd** [comment]
> If a program catches an exception and does not re-throw it, is it really an exception from the outside view

I consider it a very common and highly advisable practice to catch exceptions coming from external libraries and turn them into errors which are reported back up the call stack as the `Left` component of an `Either` or `ExceptT`.

There are other instances (eg a lock file to think of just one) where one would like to delete any existing lock file (which would raise an exception if the file was not present) and then create the new lock file. This is a case where the catching and discarding of the exception is legitimate practice and there is nothing to be gained from logging the exception.
