### ISSUE TITLE
buffering log backend

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#140]
**Is your feature request related to a problem? Please describe.**
outputting message counters in the gui

**Describe the solution you'd like**
this backend keeps a `HashMap` of `LoggerName`->`LogObject`: just the last message of the named context is kept in the map.
the map can be queried (by the gui,  first of all).

**Comment by denisshevchenko** [comment]
Temporarily moved back to `Selected`, because of #10.

**Comment by denisshevchenko** [comment]
Done in #172.
