### ISSUE TITLE
cross-compilation to Windows

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#155]
```
builder for '/nix/store/dmclfdwb79ipx19q7f3m7zdd81af3pg1-threepenny-gui-0.8.3.0-lib-threepenny-gui-x86_64-pc-mingw32.drv' failed with exit code 1
```

hydra job failed`

locally building
============
library:
`nix build -f release.nix nix-tools.libs.x86_64-pc-mingw32-iohk-monitoring.x86_64-linux`
executables: 
`nix build -f release.nix nix-tools.exes.x86_64-pc-mingw32-iohk-monitoring.x86_64-linux`
tests:
`nix build -f release.nix nix-tools.tests.x86_64-pc-mingw32-iohk-monitoring.tests.x86_64-linux`

**Comment by 365andreas** [comment]
Ran 
`nix build -f release.nix nix-tools.tests.x86_64-pc-mingw32-iohk-monitoring.tests.x86_64-linux`
after commenting out all tests but still failed.

The other two commands finished successfully.

**Comment by CodiePP** [comment]
we need @angerman 's help here
the error we see:
```
builder for '/nix/store/7zz20wgipfzgic8xdy3329xnd2a2r71b-iohk-monitoring-0.1.2.0-test-tests-x86_64-pc-mingw32.drv' failed with exit code 1; last 10 log lines:
  RUNNING TESTS for iohk-monitoring-0.1.2.0-test-tests-x86_64-pc-mingw32 via wine64
  ================================================================================
  Copying extra test libraries ...
  Copying library dependencies...
  ghc-pkg: : getDirectoryContents:openDirStream: does not exist (No such file or directory)
  Running 1 test suites...
  Test suite tests: RUNNING...
  Setup: <file descriptor: 3>: hGetContents: invalid argument (invalid byte sequence)
  <file descriptor: 3>: hGetContents: invalid argument (invalid byte sequence)
  Setup: <file descriptor: 3>: hGetContents: invalid argument (invalid byte sequence)
```
it is presumably not in our code, since that was commented out.

**Comment by CodiePP** [comment]
latest PRs by angerman made it happen! all cross-compilation targets now build.
