### ISSUE TITLE
Integration: ouroboros-network

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#21]
Edit demo-playground in `ouroboros-network` to have an initial integration with `iohk-monitoring`.

it is in branch https://github.com/input-output-hk/ouroboros-network/tree/logging-integration

-------

simplifications in `basic-tracer` to be made: https://github.com/input-output-hk/ouroboros-network/pull/298 as outlined in PR #194

**Comment by 365andreas** [comment]
https://github.com/input-output-hk/ouroboros-network/commit/8fd62a94dc923449be49cf049ea9ca04a8e95498

**Comment by 365andreas** [comment]
We should have a closeScribes which will flush the queues before terminating.
