### ISSUE TITLE
T3.1.1 requirements: define functions to be benchmarked

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#227]
deliverable: requirements

**Comment by CodiePP** [comment]
had a conversation with @Jimbo4350 :
the best way to benchmark his app is to bracket around the function `validateEpochFile`
before that, the list of epochs should be traversed using this function rather than passed to `validateEpochFiles`
this should then output some OS counters like memory, disk I/O, time per epoch, ...
additionally, there should be a way to record the UTxO size..

**Comment by denisshevchenko** [comment]
@CodiePP, could you help me please?

I see `validateEpochFile` function inside of `Features.Blockchain.init` function. That `init` function is inside of `Features.Blockchain.createBlockchainFeature` function. And this function is calling in `main` function. So, the questions: which trace should I use? `mainTrace` inside of `blockchainApp` function? Or should I create another trace?
