### ISSUE TITLE
T3.3.1 requirements: which observables to monitor; definition of thresholds

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#235]
Requirements (based on `Decisions` from #238 ):

1. Use a `TeeTrace` to duplicate the stream of values to aggregation again (to use EWMA to be able to compare, for example, `ewma.avg > stats.mean + (2 seconds) || ewma.avg < stats.mean - (2 seconds)`).

2. Define a count condition in `MEvExpr`. Use `"count"` value from stats.

3. Extend `action` to be able to define it as `CreateMessage "Warning" "Something is wrong with an epoch validation"`. This `action`-message should also refer to the value and/or the comparison (this might be tricky)..

Please note that `Decisions`  from #238 are thought to be flexible! So these requirements need to be experimented with.

**Comment by denisshevchenko** [comment]
> Define a count condition in `MEvExpr`. Use `"count"` value from stats.

Currently `MEvExpr` is this:

```
data MEvExpr = Compare Text (Operator, Measurable)
             | AND MEvExpr MEvExpr
             | OR  MEvExpr MEvExpr
             | NOT MEvExpr
```

I.e. it's just a `Compare` (or logical combination of them). We can extend it, something like this:

```
    OR
    (
        Compare "ewma.avg" (
            GT,
            (
                Plus ("stats.mean") (Seconds 2)
            )
        )
    )
    (
        Compare "ewma.avg" (
            LT,
            (
                Minus ("stats.mean") (Seconds 2)
            )
        )
    )
```

which corresponds to:

```
   ewma.avg > stats.mean + (2 seconds)
|| ewma.avg < stats.mean - (2 seconds)
```

And since we have aggregated stats, we can take `*.count` from it, to be able to:

> only monitor if number of samples > n (e.g. 10)

Again, we need to extend `MEvExpr`, for example:

```
'#aggregation.critproc.observable':
    monitor-if: (EWMA.Count > (10))
    monitor: (mean >= (42))
    actions:
        - ...
```

or

```
'#aggregation.critproc.observable':
    monitor: ((If (EWMA.Count > (10))) AND (mean >= (42)))
    actions:
        - ...
```

**Comment by denisshevchenko** [comment]
@CodiePP What do you think about it?

**Comment by denisshevchenko** [comment]
> Extend `action` to be able to define it as `CreateMessage "Warning" "Something is wrong with an epoch validation"`.

We can extend `MEvExpr` like this:

```
data MEvExpr = Compare Text (Operator, Measurable)
             | AND MEvExpr MEvExpr
             | OR  MEvExpr MEvExpr
             | NOT MEvExpr
             | CreateMessage Severity Text
```

> This `action`-message should also refer to the value and/or the comparison (this might be tricky)..

Hm... We have both value and comparison in `MonitorState`.
