### ISSUE TITLE
T3.3.3 alerting

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#237]
what actions need to be executed if a threshold is surpassed?

**Comment by denisshevchenko** [comment]
I think we can close this issue, because monitoring actions (`CreateMessage`, `SetGlobalMinimalSeverity` and `AlterSeverity`) was implemented in #236 .

**Comment by CodiePP** [comment]
having tests for these actions would make it easier to spot breaking changes in `CI`.
