### ISSUE TITLE
E7.1 devops requirements

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#239]
Output is in a form they can consume; also address system specific questions apart from log output

to be discussed:
- statsd scribe

other ideas:
- forward to https://prometheus.io
- time-series db (http://opentsdb.net/index.html)

**Comment by disassembler** [comment]
If direct prometheus integration is an option, the ideal for devops would be have an optional prometheus exporter running via cardano (normal http protocol) that could be scraped directly via prometheus. This would bypass the need to write statsd metrics, run a bridge service that receives statsd metrics and then share those metrics via HTTP. If this isn't possible, statsd would be best as that's the integration we already have working with prometheus on the old cardano-sl code base.

**Comment by disassembler** [comment]
A library that might be useful: https://github.com/fimad/prometheus-haskell

**Comment by CodiePP** [comment]
1.) EKG -> Prometheus
via https://github.com/fimad/prometheus-haskell

2.) katip -> systemd -> Graylog
katip scribe to journald: https://github.com/haskell-service/katip-libsystemd-journal, from there Graylog can fetch the logs
