### ISSUE TITLE
T7.2.6 implementation: validating test in 'CI'

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#244]
implementation of validating test
add to `CI` to check that future changes will conform to spec.

----

## testing Graylog

run `example-simple` and turn on Graylog output, redirect output from UDP <port> on localhost to UDP <port> on target host.

**Comment by CodiePP** [comment]
Denis successfully used: `socat udp-l:3456,fork,reuseaddr udp:<host>:<port>` to forward Gelf messages to an instance of Graylog

**Comment by denisshevchenko** [comment]
In terminal 1 run:

```
$ socat udp-l:3456,fork,reuseaddr udp:monitoring.devops.aws.iohkdev.io:12201
```

Then, in terminal 2 run `example-simple`. As a result, all data sent to `localhost:3456` will be redirected to `monitoring.devops.aws.iohkdev.io:12201`.
