### ISSUE TITLE
T1.1.4 API monitor external process

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#257]
obtain O/S counter for external process identified by its `PID`

----

`readCounters` gets the PID of the actual process, but it could also be passed in.
https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Counters/Linux.lhs

the PID to watch could be passed in in the configuration
maybe a new `Observer` be created?

**Comment by 365andreas** [comment]
`ObservableInstance` could be transformed to:
```haskell
data ObservableInstance = MonotonicClock
                        | MemoryStats    (Maybe ProcessID)
                        | ProcessStats   (Maybe ProcessID)
                        | NetStats       (Maybe ProcessID)
                        | IOStats        (Maybe ProcessID)
                        | GhcRtsStats
```
If nothing is given then pid will be derived from the current process.

**Comment by 365andreas** [comment]
better:
```haskell
data SubTrace = Neutral
              | UntimedTrace
              | NoTrace
              | TeeTrace LoggerName
              | FilterTrace [(DropName, UnhideNames)]
              | DropOpening
              | ObservableTraceSelf [ObservableInstance]
              | ObservableTrace ProcessID [ObservableInstance]
              | SetSeverity Severity
                deriving (Generic, Show, Read, Eq)
```

**Comment by 365andreas** [comment]
check if it has access to `/proc/pid`

**Comment by CodiePP** [comment]
then you probably do not need the above Maybe ProcessID on the counters.
