### ISSUE TITLE
T1.1.5 API capture external log items

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#258]
capture log items from external processes (in JSON representation of `LogObject`?)

may open network port or named pipe; available on all platforms (Win, Mac, Linux)

------

describe channel: 
- using `process` library, function `createPipe`
- only one direction is needed: receiving process will open pipe, originating process writes log items to this pipe.

describe protocol:
- exchange of JSON representation of `LogObject`

receiver process:
- backend which is started using `realizeFrom` gets a trace to the switchboard; forwards all received log items to this trace; prefix with new name (can be set in configuration?)

sender process:
- scribe which outputs log items in JSON to pipe

**Comment by 365andreas** [comment]
Windows and Linux named pipes are different. (https://stackoverflow.com/a/3960270)
So we may not be able to do an interoperable solution using them.
`named pipes haskell implementations`:
 * unix (http://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Files.html#v:createNamedPipe)

Linux & Windows socket implementations:
[network](http://hackage.haskell.org/package/network-3.1.0.0)

**Comment by 365andreas** [comment]
In order to use [network](http://hackage.haskell.org/package/network-3.1.0.0) a `LogObject` should be converted to & from a `ByteString` but this is easily achievable if it is a `ToJSON` & `FromJSON` instance via [encode](http://hackage.haskell.org/package/aeson-1.4.3.0/docs/Data-Aeson.html#v:encode) & [decode](http://hackage.haskell.org/package/aeson-1.4.3.0/docs/Data-Aeson.html#v:decode) respectively.

**Comment by 365andreas** [comment]
Notice in [network](http://hackage.haskell.org/package/network-3.1.0.0):
`
The proper programming model is that one Socket is handled by a single thread. If multiple threads use one Socket concurrently, unexpected things would happen. There is one exception for multiple threads vs a single Socket: one thread reads data from a Socket only and the other thread writes data to the Socket only.
`

**Comment by 365andreas** [comment]
^^ This may need some synchronization on the client (writer) side or some type of collecting all the messages to a shared queue and being sent by one thread.
