### ISSUE TITLE
T7.2.4 EKG display

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#289]
@disassembler 's request:

> in EKG stats, could we report the sync status? We have cardano.total_main_blocks in the old implementation but it just shows 0 until the node is in sync.

needs adaption in byron-proxy, EKGView

**Comment by 365andreas** [comment]
It seems that EKG has a bug in handling gauges and labels with the same prefix.

**Comment by CodiePP** [comment]
PR merged: https://github.com/input-output-hk/ouroboros-network/pull/601
