### ISSUE TITLE
Store a value in EKG of Switchboard which updates it via an IO action .

### ISSUE THREAD

**Issue by 365andreas** [input-output-hk/iohk-monitoring-framework#291]
At the current state of code, a `LogValue Text Measurable` should be `trace`d in order to add the name and the value of an interesting variable. In order to update the value of this variable we should re-`trace` it.([Measurable](https://github.com/input-output-hk/iohk-monitoring-framework/blob/be1b9d19f7a35cb2e736c1d3c5c3006f79f28e0d/iohk-monitoring/src/Cardano/BM/Data/Aggregated.lhs#L44-L51))

We must provide a way to be able to use [registerCounter](https://hackage.haskell.org/package/ekg-core-0.1.1.6/docs/System-Metrics.html#v:registerCounter), [registerGauge](https://hackage.haskell.org/package/ekg-core-0.1.1.6/docs/System-Metrics.html#v:registerGauge) and [registerLabel](https://hackage.haskell.org/package/ekg-core-0.1.1.6/docs/System-Metrics.html#v:registerLabel) which update automatically the value of the counter, gauge or label using the given action.

Proposed solution no1: Export `EKG Store` via `Switchboard` 
https://github.com/input-output-hk/iohk-monitoring-framework/blob/09ad923409da857907305b8acbb9904b94c12431/iohk-monitoring/src/Cardano/BM/Output/Switchboard.lhs#L81-L85
```haskell
data SwitchboardInternal a = SwitchboardInternal
    { sbQueue     :: TBQ.TBQueue (LogObject a)
    , sbDispatch  :: Async.Async ()
    , sbLogBuffer :: Cardano.BM.Output.LogBuffer.LogBuffer a
    }
```

**Comment by CodiePP** [comment]
I think we only want to provide `Tracer` to be able to capture and route observables.
