### ISSUE TITLE
T1.1.6 Output scribe in JSON to logging process

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#309]
we could have a lightweight logging in a process that does basic filtering and outputs `LogObject`s to a scribe that is connected to another logging instance in another process that does capturing and output to logs, monitoring, etc.

pros:
- the originating logging process can be kept quite small (`disable_` flags in cabal/stack.yaml file)
- logging is output in a central place: important for log rotation
- in the originating process logged items are still kept "lazy" until they are output to the central log process

cons:
- slow/unreliable communication?

----

**Comment by 365andreas** [comment]
A second minimal library or a new module could be created which will be responsible to write to the socket or the named pipe `LogObject`s in the form of a `Bytestring`.
On the other side a new backend could listen to the socket(s) or the named pipe(s) and forward the messages to the switchboard.

**Comment by CodiePP** [comment]
done as `TraceForwarder` writing to a `TraceAcceptor` in another process.
