### ISSUE TITLE
T7.2.5 implementation: gelf/graylog log backend

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#310]
https://docs.graylog.org/en/3.0/pages/gelf.html

* UDP transport
* JSON format (see spec above)
* can translate from katip fields to gelf fields
* test on all platforms (Linux, MacOSX, Windows)

**Comment by CodiePP** [comment]
current test:
in terminal 1 start: `nc -4 -l -u 127.0.0.1 3456` to accept UDP packets on port 3456
in terminal 2 start: `cabal new-run example-simple` to send a few log messages

**Comment by CodiePP** [comment]
@cleverca22 @disassembler could you please test this against a real instance of Graylog

**Comment by CodiePP** [comment]
still needs rebasing on `master`

**Comment by denisshevchenko** [comment]
Correct `nc` command on Linux is:

```
nc -l -u -p 3456 127.0.0.1
```

_If you see `nc: command not found`, install `netcat` package._
