### ISSUE TITLE
T9.3.2 implement routing, aggregation, monitor

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#349]
* add `UserDefinedBK Text` to `BackendKind`
* `addBackend` to the switchboard; inserts it into the list of backends; might need to restart the dispatcher
* in the future: can be used to move some of the "internal" backends to their own libraries (reduces the number of dependencies in `iohk-monitoring`)

**Comment by CodiePP** [comment]
@365andreas : missing are the ToJSON/FromJSON instances for `BackendKind`

**Comment by 365andreas** [comment]
https://github.com/input-output-hk/iohk-monitoring-framework/pull/392/commits/f4cbf0e1a93f2b7413407140955f08b069923506

**Comment by CodiePP** [comment]
now also available in `cardano-node`: https://github.com/input-output-hk/cardano-node/pull/38
