### ISSUE TITLE
Bug: prometheus does not display 'real' values

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#361]
I see on EKG: 
`real:complex.message.Error.timed.mean | 3.5568424622399645e15`

but nowhere in Prometheus output.

**Comment by 365andreas** [comment]
In `example-complex`.

**Comment by 365andreas** [comment]
Reals are stored as `Label`s in `EKG` as it cannot store real numbers and [ekg-prometheus-adapter](https://hackage.haskell.org/package/ekg-prometheus-adapter-0.1.0.3) ignores any `Label` inside ekg store.

**Comment by 365andreas** [comment]
I can see 2 possible solutions:
1. We can change the function from [ekg-prometheus-adapter](https://hackage.haskell.org/package/ekg-prometheus-adapter-0.1.0.3)
2. We can create an independent `prometheus` store and forward the items that arrive in `EKG` to `prometheus`.

**Comment by CodiePP** [comment]
I think it only needs some proper conversion. I see in prometheus:
```
ns:complex_message_Debug_timed_max  1.561453432464649e18
```
which looks like a real value.
so any value starting with "real:" can be tried to be converted to a `Double` and then output to Prometheus. (and, "ns:", others ?)

**Comment by 365andreas** [comment]
> I think it only needs some proper conversion. I see in prometheus:
> 
> ```
> ns:complex_message_Debug_timed_max  1.561453432464649e18
> ```
> 
> which looks like a real value.
> so any value starting with "real:" can be tried to be converted to a `Double` and then output to Prometheus. (and, "ns:", others ?)

This is `Nanoseconds` which is translated for [ekg](https://hackage.haskell.org/package/ekg) in `Gauge` (integer-valued gauges) and then all the `Gauge`s from [ekg](https://hackage.haskell.org/package/ekg) are translated to [prometheus](https://hackage.haskell.org/package/prometheus)' `Gauge` which is a double-valued gauge.

`Label`s of [ekg](https://hackage.haskell.org/package/ekg) are ignored by the [ekg-prometheus-adapter](https://hackage.haskell.org/package/ekg-prometheus-adapter-0.1.0.3).
https://github.com/adinapoli/ekg-prometheus-adapter/blob/bb482c9918cde40a5ac475fef4c67c8b5436ac09/src/System/Remote/Monitoring/Prometheus.hs#L88
