### ISSUE TITLE
Threadid `tid` in `LoMeta` should be provided by the logger

### ISSUE THREAD

**Issue by coot** [input-output-hk/iohk-monitoring-framework#362]
**Is your feature request related to a problem? Please describe.**
The user of `Trace (LogObject a)` is forced to supply `tid`.  I presume this is `ThreadId`. It would be better if the end user was not forced to provide it, but the monadic context of the logger should provide it.  

We already see duplication in our own code base to deal with this:
https://github.com/input-output-hk/ouroboros-network/pull/599/commits/782a59e3e6610451deaa2b74f76d8228510d9923#diff-3e1dc6fdd7939d85d432a54b680386e8L46
https://github.com/input-output-hk/ouroboros-network/pull/607/commits/85cd0663b43912f1005ee58d33774623873d4ebb#diff-8171140a5b06764328b5354aebb2f859R599

**Describe the solution you'd like**
Consider adding the @avieth's `convertTrace` to the interface of this library, or some similar function.

@avieth @karknu

**Comment by coot** [comment]
Alex's solution also takes care of current time, which as `ThreadId` should not be provided by the end user but evaluated in the `Tracer`'s codomain monadic context.

**Comment by dcoutts** [comment]
Information that is already available in the monad context should be picked up by the tracer itself. It should not need to be supplied explicitly at the trace point in the code.

Examples here include the time and the thread ID. These can be obtained by the monadic tracer action directly.

Indeed there's *more* available to the tracer itself than is available at the trace point, because the tracer knows the concrete monad it is in, whereas the trace point in the code may not.

For example consider the time. The context of the trace point may be just `Monad` or `MonadSTM` or something, but not `MonadTime`. So the trace point cannot supply a time. But when the code is used later it may be used at type `IO` and so now the tracer can trivially obtain the time at the point where the tracer is used.

**Comment by coot** [comment]
Right, with time it is more tricky as it is not provided in all contexts; We could provide:
```
traceThreadId :: MonadFork m => Trace m (LogObject a) -> Trace m (time, Severity, ..., a)
```
The caller could decide what to do with `time` and other parameters using `contramap`, and another function:
```
traceTime :: MonadTime m => Trace m (time, Severity, ...) -> Trace m (Severity, ...)
```
which allows to trace the time rather than ignore it.

Does it forces dependency of `iohk-monitoring-framework` on `io-sim-classes`? Then we can provide them in `ouroboros-network` directly for our use case, and likely for the benefit of `ouroboros-consensus` as well.

`IO` versions of these function (or just a single one which does both things) can be exposed here without forcing any dependencies.

**Comment by karknu** [comment]
> For example consider the time. The context of the trace point may be just Monad or MonadSTM or something, but not MonadTime. So the trace point cannot supply a time. 

`MonadTime` only provides a monotinic timestamp through `getMonotonicTime` for logging we need time that is meaningful externally, i.e a UTCTime, such as supplied by `getCurrentTime`

**Comment by CodiePP** [comment]
in `IO` you may want to use `mkLOMeta`:
https://github.com/input-output-hk/iohk-monitoring-framework/blob/ba3497c762561c6c4e312d3a766ecce2337cc23c/iohk-monitoring/src/Cardano/BM/Data/LogItem.lhs#L88

**Comment by CodiePP** [comment]
@365andreas already did investigate how to create the structure LOMeta in a `Sim` context:
https://github.com/input-output-hk/iohk-monitoring-framework/blob/ba3497c762561c6c4e312d3a766ecce2337cc23c/iohk-monitoring/src/Cardano/BM/Data/Tracer.lhs#L104
the idea is to provide an instance of `ToLogObject`

**Comment by coot** [comment]
I see, so what I am asking is already done by `ToLogObject` type class :).

The problem with the instance for `Sim` is that in `ouroboros-network` it would be an orphaned instance and adding `iohk-monitoring-framework` as a depenency of `io-sim-classes` is not a good option, but we can provide `toLogObjectIO` and `toLogObjectSim` without adding `ToLogObject` constraint.
