### ISSUE TITLE
T9.3.4 live view

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#384]
implementation of live view

live view of captured observables:
![Untitled drawing](https://user-images.githubusercontent.com/14063171/60418265-cca83280-9be2-11e9-9284-af3b240e99d8.png)

using `ansi-terminal-game` library

**Comment by denisshevchenko** [comment]
TODO:

[ ] Mempool progress bar
[ ] CPU usage progress bar
[ ] Memory usage progress bar
[ ] Disk usage progress bars (both for `R` and `W`)
[ ] Network usage progress bars (both for `In` and `Out`)
[ ] `version`
[ ] `commit`
[ ] `uptime`
[ ] `block height`
[ ] `minted`
[ ] `transactions`
[ ] `peers connected`
[ ] `max network delay`

**Comment by 365andreas** [comment]
@ksaric ^^

**Comment by denisshevchenko** [comment]
![alt text](https://i.imgur.com/7181TGq.png "Logo Title Text 1")

![alt text](https://i.imgur.com/r3gHWhV.png "Logo Title Text 1")
