### ISSUE TITLE
Using bracketObserveIO with setMonitors

### ISSUE THREAD

**Issue by rvl** [input-output-hk/iohk-monitoring-framework#391]
I would like to trace a value with `bracketObserveIO`, then use `setMonitors` to log a message if the bracket duration is greater than a certain time.

Where `bracketObserveIO` is used around `runQuery`:
```haskell
traceQuery <- appendName "query" trace
let observe :: IO a -> IO a
    observe = bracketObserveIO logConfig traceQuery Debug "query"
-- ...
```

Excerpt from the log config setup:
```haskell
CM.setSubTrace logConfig "query"
    (Just $ CM.ObservableTraceSelf [MonotonicClock])

-- This monitor should always trigger.
CM.setMonitors logConfig $ HM.singleton
        "query.query"
        ( Nothing
        , Compare "monoclock" (GE, (OpMeasurable (Seconds 0)))
        , [CreateMessage Info "runQuery monitor works"]
        )
```

The log objects which are produced:
```haskell
[
LogObject { loName = "query.query"
          , loMeta = LOMeta {tstamp = 2019-07-02 09:24:42.544871451 UTC, tid = "ThreadId 646", severity = Debug, privacy = Confidential}
          , loContent = ObserveOpen (CounterState {csCounters = [Counter {cType = MonotonicClockTime, cName = "monoclock", cValue = 920729072625 \181s}]})},
LogObject { loName = "query"
          , loMeta = LOMeta {tstamp = 2019-07-02 09:24:42.544879467 UTC, tid = "ThreadId 646", severity = Debug, privacy = Public}
          , loContent = LogMessage "SELECT \"wallet_id\" FROM \"wallet\" ORDER BY \"wallet_id\""},
LogObject { loName = "query.query"
          , loMeta = LOMeta {tstamp = 2019-07-02 09:24:42.544898976 UTC, tid = "ThreadId 646", severity = Debug, privacy = Confidential}
          , loContent = ObserveClose (CounterState {csCounters = [Counter {cType = MonotonicClockTime, cName = "monoclock", cValue = 920729072652 \181s}]})},
LogObject { loName = "query.query", loMeta = LOMeta {tstamp = 2019-07-02 09:24:42.544898976 UTC, tid = "ThreadId 646", severity = Debug, privacy = Confidential}
          , loContent = ObserveDiff (CounterState {csCounters = [Counter {cType = MonotonicClockTime, cName = "monoclock", cValue = 27 \181s}]})
          }
]
```

The monitor doesn't trigger.

**Comment by CodiePP** [comment]
the need for more message types in monitoring expressions arose.
i.e. counters in ObserveOpen, ObserveClose, ObserveDiff; extracted as `Measurable`

**Comment by rvl** [comment]
Another thing I was confused about, though it may be a separate issue.

```haskell
traceQuery <- appendName "query" trace
let observe :: IO a -> IO a
    observe = bracketObserveIO logConfig traceQuery Debug "query"
observe $ runQuery ...
```

For the `name` argument of `bracketObserveIO`, it needs to be the same name that `traceQuery` has. Otherwise nothing gets logged. But then the LogObjects come out with name `query.query`.

**Comment by 365andreas** [comment]
@rvl  Are you using the latest master? This was changed https://github.com/input-output-hk/iohk-monitoring-framework/commit/1cbe71411b1267709f32b910772f337be605f00c.

**Comment by 365andreas** [comment]
`bracketObserveIO logConfig traceQuery Debug "query"` where "query" is the full name of the trace.

**Comment by 365andreas** [comment]
@rvl Do you have a branch working on this?

**Comment by rvl** [comment]
Hi @365andreas 

> Are you using the latest master?

Yes more or less. We are currently on e2dc8b2160bb2ccd1ef9817a6498cda06ad36580.

> Do you have a branch working on this?

Yes, cardano-wallet master.

* I'm using `bracketObserveIO` in [`Sqlite.hs`](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/DB/Sqlite.hs)
* And `setMonitors` in [`SqliteSpec.hs`](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs). This is a test case, and I want to check that the observer works by adding a monitor onto it.

> where "query" is the full name of the trace.

Maybe I'm using it wrong but I don't think it works very well to use the full name of the trace in `bracketObserveIO`. The name should be relative to the given trace.

**Comment by denisshevchenko** [comment]
https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs#L284-L286

**Comment by 365andreas** [comment]
@rvl How could I reproduce it. I am trying `stack exec cardano-wallet-http-bridge launch`

**Comment by CodiePP** [comment]
@rvl can you confirm that the modification now works in your monitoring?

**Comment by rvl** [comment]
@365andreas I have tried to implement monitoring only in a test case (`SqliteSpec.hs`). This PR contains the update to iohk-monitoring: input-output-hk/cardano-wallet#510

It can be run with:

    stack test cardano-wallet-core:test:unit --ta "--match \"Sqlite observables\""
