### ISSUE TITLE
T9.3.4.1 Make `brick` be optional so we can cross-compile

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/iohk-monitoring-framework#403]
Dependency on `vty` should be optional, and more generally make sure that the libs can build with Windows CI. If it means disabling things that are not needed by Daedalus users then that's ok. We expect exchanges and stake pools to use unix (linux, osx or bsd).

https://github.com/input-output-hk/iohk-monitoring-framework/issues/384

**Comment by 365andreas** [comment]
`brick` is already a conditional dependency:
https://github.com/input-output-hk/cardano-node/blob/3c3bde0e1c9ab82801522c214261b9f52a2a9ab8/cardano-node.cabal#L113

**Comment by angerman** [comment]
@365andreas right, the issue seems to be that `LiveView` is pulled in unconditionally as a dependency in some other module, see the log here: https://hydra.iohk.io/build/965038/nixlog/1

**Comment by 365andreas** [comment]
https://github.com/input-output-hk/cardano-node/pull/56
