### ISSUE TITLE
privacy filtering

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#41]
* there are two distinctions of log file output: `private` | `public`
  * private := this information is to be kept private, not shared across the network
  * public := this information only contains public information, and thus may be shared

* all log file outputs are `public`, thus may not contain any private information
* a log file output can be flagged `private` deliberately in the responsibility of dev/user/..
* behaviour of log outputs marked `public`:
  * filter out messages marked `private`
* behaviour of log outputs marked `private`:
  * log all messages, including those marked `private`.

* functions `logDebug, logInfo, ..` mark the log item as `public`, thus may not reach the `private` outputs
* functions `logDebugS, logInfoS, ..` mark the log item as `private`, thus may end up in any log output

**Comment by 365andreas** [comment]
Also, there is no need anymore to restrict messages to be logged only to public files.
