### ISSUE TITLE
output selection

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#42]

**Comment by CodiePP** [comment]
we already have output selection in place:
from `EKGView` we route items to be displayed to a trace with name `#ekgview.<context name>`.
the same goes for `Aggregation`: `#aggregation.<context name>`.

do we need more?

**Comment by 365andreas** [comment]
No and we also can direct different namespaces to different files.

**Comment by CodiePP** [comment]
this has been solved in various commits.
