### ISSUE TITLE
Provide extra context for ekg exceptions

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/iohk-monitoring-framework#457]
If two nodes accidentally are configured to use the same port for their ekg then we get the only semi-informative message:
```
cardano-node: Network.Socket.bind: resource busy (Address already in use)
```
Just need to wrap all ekg startup exceptions in an exception type that identifies that it's from ekg, e.g. something like
```
data EkgFailure = EkgStartupFailure IOException deriving Show
instance Exception EkgFailure
```
```
    handle <- forkServer host port
               `catch` throwIO . EkgStartupFailure
```

**Comment by dcoutts** [comment]
Apparently the same thing is likely to be possible with Prometheus, so we might apply the same solution.

**Comment by deepfire** [comment]
I wonder if we want a generic `BackendFailure` with backend-specific cases, instead of an assortment of backend-specific types?

**Comment by deepfire** [comment]
How about this approach -- just as an illustration -- @CodiePP, @dcoutts: https://github.com/input-output-hk/iohk-monitoring-framework/pull/462/files

**Comment by CodiePP** [comment]
I think the case in EKGView should be covered.
https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/plugins/backend-ekg/src/Cardano/BM/Backend/EKGView.lhs#L219
in the function "realizeFrom" we have access to a Trace back to the switchboard to which we could trace an error message and abort the initialisation of the EKG backend.

**Comment by deepfire** [comment]
> I think the case in EKGView should be covered.

Absolutely -- I didn't do it because I wanted us to agree on the general shape of the solution, before I go to town about implementing it.

**Comment by deepfire** [comment]
Implemented in https://github.com/input-output-hk/iohk-monitoring-framework/pull/462
