### ISSUE TITLE
Allow binding Prometheus to ip address

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/iohk-monitoring-framework#458]
**Is your feature request related to a problem? Please describe.**
Prometheus is hardcoded to run on localhost. This should be configurable
**Describe the solution you'd like**
Configuration for hasPrometheus should take multiaddr format instead of just a port. Eg /ip4/10.0.0.5/tcp/12798
**Describe alternatives you've considered**
Nginx reverse proxy is what we're doing for this release, but it complicates the setup, especially on hosts using nginx publicly like explorer.
**Additional context**

**Comment by deepfire** [comment]
Ok, so Prometheus can bind to `::1` using its own address spec type, @disasm, @CodiePP .

We'd like to follow the most straightforward implementation in this case, so perhaps we should just make hostname configurable?

**Comment by disassembler** [comment]
do we need a hostname at all? Primarily, I just need to be able to curl it from the remote prometheus server. current work-around is to run an nginx proxy, but this is extra overhead I'd like to avoid.

**Comment by CodiePP** [comment]
yes, I think we should be able to indicate "127.0.0.1" for the listening address/interface.
