### ISSUE TITLE
tracer transformer with delayed output of repeated messages

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#459]
messages of the same type may be emitted by processes that occasionally occur to cleanup the db, for example.
we need a tracer transformer which keeps in its internal state the last message type and a counter.

if the traced message matches the state's last msg type, then the counter is increased and the message dropped.
alternative, a traced message (not matching the last msg type) resets the counter to 1 and sets the last msg type to the one of the traced msg; if the counter was > 1 a new message is output with the count and the type of traced messages suppressed. the new message is passed on to subsequent tracers.

### variations
the tracer transformer could be parameterised to also reset and output the counter after:
* n traced messages (of the same type)
* t time passed (e.g. 30 seconds)

**Comment by deepfire** [comment]
This needs a design choice.

First, an assumption -- there's no way to introduce state into the tracer, except via the underlying monad.

So there's the choice of the monad, then:

1. `IO` -- then we have two further options:
  - global state, implying we do extra locking
  - or we go thread-local,
2. `MonadST` -- but that involves the problem of dealing with monad stacks, and we probably don't want the coupling that would result in.

Efficiency is important, so in case we're going with the option #1, then thread-local state is going to be right solution, IMO -- but that is also going to require thread-local init for this state, which is error-prone.

**Comment by deepfire** [comment]
There's an implicit option #3, which would avoid the coupling problem of option #2 -- 

3. Rewrite the entire software stack to use some form of extensible effects (such as [1]), so that we can have multiple, independent state layers -- so we don't break abstraction.

--
1. http://hackage.haskell.org/package/fused-effects

**Comment by avieth** [comment]
This seems to me like a very weird feature request. Isn't the problem that the user of the tracer is being too verbose? If it's inappropriate to have all of these apparently duplicate messages, shouldn't the program which produces them be changed to not do so?

**Comment by CodiePP** [comment]
the use case: https://github.com/input-output-hk/cardano-node/pull/309
tons of messages, potentially.

**Comment by deepfire** [comment]
The PR is ready for review: https://github.com/input-output-hk/iohk-monitoring-framework/pull/466
