### ISSUE TITLE
Add transaction tracers to ChainDB for tracing how long does it take for a tx to be integrated into a block

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/iohk-monitoring-framework#467]
The `cardano-ledger` functions are used in `Ouroboros.Consensus.Ledger.Byron.*`, for things like block and transaction validation.
The ledger consists mainly of pure code, so tracing there will be quite hard, even though the `Tracer m event` (where `m` is a monad) validation parts are pure as in the monadic context has not been defined (yet), but they are monadic.

We are looking at places where we could add microbenchmarking.
So trying to figure out how much the validation of a block/epoch/whatever takes, how much time do these operations take.

**This issue is concerned with measuring with how long does it take for a transaction to be forged into a block.**

In `Ouroboros.Consensus.Ledger.Abstract` the `UpdateLedger` type class is defined with methods to apply (validate) blocks. These are all pure. And this is a feature, not something the consensus teem is keen to step away from.

So this could be done at a higher level- the `ChainDB`. It will validate blocks during chain selection in an `IOLike` context.

Some examples of where that could be done are in `LedgerDB.InMemory`, namely `ledgerDbPush` and `(re)applyBlock`.

**Comment by CodiePP** [comment]
in the logs I follow these events: `TraceForgeEvent` to `TraceAddBlockEvent.SwitchedToChain`
