### ISSUE TITLE
Add ability to build without systemd support

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/iohk-monitoring-framework#523]
**Is your feature request related to a problem? Please describe.**
Currently code, that decides weather `systemd` integration is enabled depends only on the target platform itself

```haskell
#ifdef LINUX
import           Cardano.BM.Scribe.Systemd
#endif
```

many won't rely on using `systemd` including `journald` in their deployments even though they may be running on Linux platform.

**Describe the solution you'd like**
Inclusion of `systemd` should be fully voluntary during build process so that the overall application footprint and this attack surface is lower; additional `#IFDEF` should be introduced to disable `systemd` integration on Linux platform like in Docker deployment.

**Describe alternatives you've considered**
Installing unnecessary dependencies that increase application footprint and attack surface for no good reason.

**Additional context**

**Comment by dcoutts** [comment]
Is this an actual problem running in an environment without systemd? It should work fine to compile systemd support in but not to use it at runtime. We try to avoid CPP-based conditional where we can.

Can you describe the problem you run into with systemd support being compiled it?

**Comment by angerman** [comment]
@mark-stopka input-output-hk/cardano-node#911 should fix this.
