### ISSUE TITLE
Bug: contra-tracer package shadows one on Hackage

### ISSUE THREAD

**Issue by phadej** [input-output-hk/iohk-monitoring-framework#626]
... and is vastly different. https://hackage.haskell.org/package/contra-tracer

Please either use the `contra-tracer` from Hackage, or rename your package.

**Comment by phadej** [comment]
ping

**Comment by CodiePP** [comment]
> ping

pong. right.

**Comment by phadej** [comment]
Then I won't wait for this to be resolved anymore.

**Comment by erikd** [comment]
I would like to keep this open so that it does get fixed.

**Comment by phadej** [comment]
Please open own issue. I don't want this issue staying on my open issue list.

**Comment by erikd** [comment]
https://github.com/input-output-hk/iohk-monitoring-framework/issues/632
